### ISSUE TITLE
Mistake function argument in sample script(readme.md)

### ISSUE THREAD

**Issue by anjasnewbie** [xros/py_django_crack#3]
just a little help if there is someone had confuse like me,
please check get_base64_hashed function argument .
this is correct one.
get_base64_hashed('user_passw0rd', **salt**, _iter_, hashlib.sha256)

not this one
b = get_base64_hashed('user_tried_password', _iter_, **salt**, hashlib.sha256)

**Comment by xros** [comment]
Thanks for the notice. That's my typo in the document. Doc updated. Codes are fine.
